_commit: fe21eee73f47a659640e02590a3d72ca82f2ca35
_src_path: cookiecutter-monarch-ingest
copyright_year: '2026'
email: info@monarchinitiative.org
full_name: Monarch Initiative
github_handle: monarch-initiative
github_org: monarch-initiative
license: BSD-3-Clause
project_description: Conversion of ClinGen variant and gene-disease data to Biolink model format
project_name: clingen-ingest
project_slug: clingen_ingest
